---
- name: Install Nginx service
  hosts: all
  become: true
  tasks:
    - name: Install Nginx service
      ansible.builtin.package:
        name: nginx

    - name: Ensure Nginx service is started
      ansible.builtin.service:
        name: nginx
        state: started
